// name of shares and related server
export const sharesData = {
      "ECP"   : ["ecorp"                        ]
    , "MGCP"  : ["megacorp"                     ]
    , "BLD"   : ["blade"                        ]
    , "CLRK"  : ["clarkinc"                     ]
    , "OMTK"  : ["omnitek"                      ]
    , "FSIG"  : ["4sigma"                       ]
    , "KGI"   : ["kuai-gong"                    ]
    , "FLCM"  : ["fulcrumtech", "fulcrumassets" ]
    , "STM"   : ["stormtech"                    ]
    , "DCOMM" : ["defcomm"                      ]
    , "HLS"   : ["helios", "The-Cave"           ]
    , "VITA"  : ["vitalife"                     ]
    , "ICRS"  : ["icarus"                       ]
    , "UNV"   : ["univ-energy"                  ]
    , "AERO"  : ["aerocorp"                     ]
    , "OMN"   : ["omnia"                        ]
    , "SLRS"  : ["solaris"                      ]
    , "GPH"   : ["global-pharm"                 ]
    , "NVMD"  : ["nova-med"                     ]
    , "WDS"   : [                               ]
    , "LXO"   : ["lexo-corp"                    ]
    , "RHOC"  : ["rho-construction"             ]
    , "APHE"  : ["alpha-ent"                    ]
    , "SYSC"  : ["syscore"                      ]
    , "CTK"   : ["comptek"                      ]
    , "NTLK"  : ["netlink"                      ]
    , "OMGA"  : ["omega-net"                    ]
    , "FNS"   : ["foodnstuff"                   ]
    , "JGN"   : ["joesguns"                     ]
    , "SGC"   : ["sigma-cosmetics"              ]
    , "CTYS"  : ["catalyst"                     ]
    , "MDYN"  : ["microdyne"                    ]
    , "TITN"  : ["titan-labs"                   ]
};
